.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015" 
.nh
.ad l


.SH NAME
.PP
kubeadm init phase upload\-config kubeadm \- Upload the kubeadm ClusterConfiguration to a ConfigMap


.SH SYNOPSIS
.PP
\fBkubeadm init phase upload\-config kubeadm\fP [OPTIONS]


.SH DESCRIPTION
.PP
Upload the kubeadm ClusterConfiguration to a ConfigMap called kubeadm\-config in the kube\-system namespace. This enables correct configuration of system components and a seamless user experience when upgrading.

.PP
Alternatively, you can use kubeadm config.


.SH OPTIONS
.PP
\fB\-\-config\fP=""
    Path to a kubeadm configuration file.

.PP
\fB\-\-kubeconfig\fP="/etc/kubernetes/admin.conf"
    The kubeconfig file to use when talking to the cluster. If the flag is not set, a set of standard locations can be searched for an existing kubeconfig file.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-rootfs\fP=""
    [EXPERIMENTAL] The path to the 'real' host root filesystem.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH EXAMPLE
.PP
.RS

.nf
  # upload the configuration of your cluster
  kubeadm init phase upload\-config \-\-config=myConfig.yaml

.fi
.RE


.SH SEE ALSO
.PP
\fBkubeadm\-init\-phase\-upload\-config(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
