.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015" 
.nh
.ad l


.SH NAME
.PP
kubeadm alpha kubeconfig user \- Output a kubeconfig file for an additional user


.SH SYNOPSIS
.PP
\fBkubeadm alpha kubeconfig user\fP [OPTIONS]


.SH DESCRIPTION
.PP
Output a kubeconfig file for an additional user.

.PP
Alpha Disclaimer: this command is currently alpha.


.SH OPTIONS
.PP
\fB\-\-apiserver\-advertise\-address\fP=""
    The IP address the API server is accessible on

.PP
\fB\-\-apiserver\-bind\-port\fP=6443
    The port the API server is accessible on

.PP
\fB\-\-cert\-dir\fP="/etc/kubernetes/pki"
    The path where certificates are stored

.PP
\fB\-\-client\-name\fP=""
    The name of user. It will be used as the CN if client certificates are created

.PP
\fB\-\-org\fP=[]
    The orgnizations of the client certificate. It will be used as the O if client certificates are created

.PP
\fB\-\-token\fP=""
    The token that should be used as the authentication mechanism for this kubeconfig, instead of client certificates


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-rootfs\fP=""
    [EXPERIMENTAL] The path to the 'real' host root filesystem.

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH EXAMPLE
.PP
.RS

.nf
  # Output a kubeconfig file for an additional user named foo
  kubeadm alpha kubeconfig user \-\-client\-name=foo

.fi
.RE


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-kubeconfig(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
